/* Untyped file generated by genType. */

const Curry = require('bs-platform/lib/js/curry.js');

const ReCounterBS = require('./ReCounter.bs');

const ReasonReact = require('reason-react/src/ReasonReact.js');

export const ReCounter = ReasonReact.wrapReasonForJs(
  ReCounterBS.component,
  (function _(jsProps) {
     return Curry._2(ReCounterBS.make, jsProps.count, jsProps.children);
  }));

export default ReCounter;
