/* Untyped file generated by genType. */

const Curry = require('bs-platform/lib/js/curry.js');

const ReasonReact = require('reason-react/src/ReasonReact.js');

const layoutBS = require('./layout.bs');

export const layout = ReasonReact.wrapReasonForJs(
  layoutBS.component,
  (function _(jsProps) {
     return Curry._3(layoutBS.make, jsProps._location, [jsProps.file.title, jsProps.file.description, jsProps.file.keywords], jsProps.children);
  }));

export default layout;
