/* Untyped file generated by genType. */

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

import * as aboutBS from './about.bs';

export const about = ReasonReact.wrapReasonForJs(
  aboutBS.component,
  (function _(jsProps) {
     return aboutBS.make(jsProps.children);
  }));

export default about;
