/* Untyped file generated by genType. */

const ReasonReact = require('reason-react/src/ReasonReact.js');

const page_404BS = require('./page_404.bs');

export const page_404 = ReasonReact.wrapReasonForJs(
  page_404BS.component,
  (function _(jsProps) {
     return page_404BS.make(jsProps.children);
  }));

export default page_404;
