/* Untyped file generated by genType. */

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

import * as page_404BS from './page_404.bs';

export const page_404 = ReasonReact.wrapReasonForJs(
  page_404BS.component,
  (function _(jsProps) {
     return page_404BS.make(jsProps.children);
  }));

export default page_404;
